### ISSUE TITLE
CS0103 C# The name does not exist in the current context

### ISSUE THREAD

**Issue by OleksandrFomenko** [dotnet/AspNetCore.Docs.ru-ru#75]
updated Program.cs file has mistake CS0103 C# The name "Host" does not exist in the current context

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Работа с базой данных и ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @OleksandrFomenko
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @OleksandrFomenko, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17265. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
